services:
  product-service-db:
    image: postgres:18-alpine
    container_name: product_service_postgres
    environment:
      - POSTGRES_DB=${PRODUCT_SERVICE_DB_NAME}
      - POSTGRES_USER=${PRODUCT_SERVICE_DB_USERNAME}
      - POSTGRES_PASSWORD=${PRODUCT_SERVICE_DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "${PRODUCT_SERVICE_DB_PORT}:5432"
    volumes:
      - product_service_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  payment-system-product-service:
    image: ghcr.io/yuryshakhau1/payment-system-product-service:latest
    container_name: payment_system_product_service
    profiles:
      - docker
    ports:
      - "${PRODUCT_SERVICE_PORT}:${PRODUCT_SERVICE_PORT}"
    environment:
      - PRODUCT_SERVICE_PORT=${PRODUCT_SERVICE_PORT}
      - PRODUCT_SERVICE_DB_NAME=${PRODUCT_SERVICE_DB_NAME}
      - PRODUCT_SERVICE_DB_USERNAME=${PRODUCT_SERVICE_DB_USERNAME}
      - PRODUCT_SERVICE_DB_PASSWORD=${PRODUCT_SERVICE_DB_PASSWORD}
      - PRODUCT_SERVICE_DB_PORT=${PRODUCT_SERVICE_DB_PORT}
    depends_on:
      - product-service-db

volumes:
  product_service_postgres_data:
